# Generated by Django 2.0.3 on 2018-03-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
