# Generated by Django 2.0.3 on 2018-03-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('length', models.TimeField(default='0:00:00')),
                ('year', models.IntegerField(null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('album_logo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=25)),
                ('year', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('artist_logo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Chart_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField()),
                ('weeks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('popular_artists', models.CharField(max_length=100)),
                ('popular_tracks', models.CharField(max_length=100)),
                ('genre_logo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Top_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('language', models.CharField(max_length=25)),
                ('length', models.TimeField(default='0:00:00')),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Artist')),
                ('charts', models.ManyToManyField(blank=True, null=True, through='search.Chart_member', to='search.Top_Chart')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='chart_member',
            name='top_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Top_Chart'),
        ),
        migrations.AddField(
            model_name='chart_member',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Track'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Genre'),
        ),
    ]
