# Generated by Django 2.0.3 on 2018-03-19 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('album_logo', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=25)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('artist_logo', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('popular_artists', models.CharField(max_length=100)),
                ('popular_tracks', models.CharField(max_length=100)),
                ('genre_logo', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=25)),
                ('length', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Genre'),
        ),
    ]
