# Generated by Django 2.0.3 on 2018-03-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField()),
                ('weeks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Top_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='album',
            name='length',
            field=models.TimeField(default='0:00'),
        ),
        migrations.AddField(
            model_name='artist',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.TimeField(default='0:00'),
        ),
        migrations.AlterField(
            model_name='track',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chart_member',
            name='top_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Top_Chart'),
        ),
        migrations.AddField(
            model_name='chart_member',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Track'),
        ),
        migrations.AddField(
            model_name='track',
            name='charts',
            field=models.ManyToManyField(through='search.Chart_member', to='search.Top_Chart'),
        ),
    ]
