# Generated by Django 2.0.3 on 2018-03-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_track_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
